### ISSUE TITLE
Add way to get configurations

### ISSUE THREAD

**Issue by okt-limonikas** [ts-factory/bublik#83]
When generating CMD for new bug button I try to generate for each value in `special_categories` from details
`special_categories` are defined in config it seems

It is incorrect but I have no way to do it properly

We should add new key to details like `configurations` or something so we can generate CMD for configurations without generating CMD for values like `TS_SET` etc...

should probably add to run details endpoint?

Related to https://github.com/ts-factory/bublik-ui/issues/174

**Comment by ol-nata** [comment]
Configurations are available under the `Configuration` key in `special_categories`.
