### ISSUE TITLE
Update the requirements

### ISSUE THREAD

**Issue by ol-nata** [ts-factory/bublik#90]
To address vulnerabilities, improve performance, and enhanced capabilities, it is necessary to update the versions of the libraries and packages used. In particular, it is necessary to migrate to a newer version of Django (5.0.0+).

**Comment by okt-kostik** [comment]
Do you have a preliminary branch that we can test?

We were expecting this to happen, but we also double-checked python requirements and migration for our deployment might be problematic.

So we'd appreciate a branch or something we can try early to try and solve IT issues.

**Comment by ol-nata** [comment]
> Do you have a preliminary branch that we can test?

https://github.com/ol-nata/bublik/tree/update/requirements
